// <auto-generated />
using System;
using GameTest.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameTest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822085032_FixWeaponTemporaryUpgradeLevelKey")]
    partial class FixWeaponTemporaryUpgradeLevelKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameTest.Domain.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Arenas");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.CatProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("StatId");

                    b.ToTable("CatProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.CatStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CatStats");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.EnemyProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("StatId");

                    b.ToTable("EnemyProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.EnemyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnemyStats");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalKills")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Bonus")
                        .HasColumnType("float");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<float?>("NextLevelBonus")
                        .HasColumnType("float");

                    b.Property<int?>("NextLevelPrice")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerLevels");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UnitId");

                    b.ToTable("PlayerUnits");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerUnitProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("NextLevelPrice")
                        .HasColumnType("int");

                    b.Property<float?>("NextLevelValue")
                        .HasColumnType("float");

                    b.Property<int>("PlayerUnitId")
                        .HasColumnType("int");

                    b.Property<int>("UnitPropertyId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlayerUnitId");

                    b.HasIndex("UnitPropertyId");

                    b.ToTable("PlayerUnitProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponId");

                    b.ToTable("PlayerWeapons");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerWeaponProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("NextLevelPrice")
                        .HasColumnType("int");

                    b.Property<float?>("NextLevelValue")
                        .HasColumnType("float");

                    b.Property<int>("PlayerWeaponId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.Property<int>("WeaponPropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerWeaponId");

                    b.HasIndex("WeaponPropertyId");

                    b.ToTable("PlayerWeaponProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("int");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("char(36)");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("LevelReached")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.HasIndex("UnitId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartWeaponId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.UnitProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatId");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.UnitStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnitStats");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Wave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndSecond")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StartSecond")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Waves");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.WeaponProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponProperties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.WeaponStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeaponStats");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.CatProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Cat", "Cat")
                        .WithMany("Properties")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.CatStat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Enemy", b =>
                {
                    b.OwnsOne("GameTest.Domain.ValueObjects.EnemyLoot", "Loot", b1 =>
                        {
                            b1.Property<int>("EnemyId")
                                .HasColumnType("int");

                            b1.HasKey("EnemyId");

                            b1.ToTable("Enemies");

                            b1.WithOwner()
                                .HasForeignKey("EnemyId");

                            b1.OwnsOne("GameTest.Domain.ValueObjects.ExperienceRange", "Experience", b2 =>
                                {
                                    b2.Property<int>("EnemyLootEnemyId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("ExperienceMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("ExperienceMin");

                                    b2.HasKey("EnemyLootEnemyId");

                                    b2.ToTable("Enemies");

                                    b2.WithOwner()
                                        .HasForeignKey("EnemyLootEnemyId");
                                });

                            b1.OwnsOne("GameTest.Domain.ValueObjects.GoldRange", "Gold", b2 =>
                                {
                                    b2.Property<int>("EnemyLootEnemyId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("GoldMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("GoldMin");

                                    b2.HasKey("EnemyLootEnemyId");

                                    b2.ToTable("Enemies");

                                    b2.WithOwner()
                                        .HasForeignKey("EnemyLootEnemyId");
                                });

                            b1.OwnsMany("GameTest.Domain.ValueObjects.ItemDrop", "Items", b2 =>
                                {
                                    b2.Property<int>("EnemyLootId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("ItemId");

                                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b2.Property<int>("ItemId"));

                                    b2.Property<float>("Chance")
                                        .HasColumnType("float")
                                        .HasColumnName("Chance");

                                    b2.HasKey("EnemyLootId", "ItemId");

                                    b2.ToTable("ItemDrop");

                                    b2.WithOwner()
                                        .HasForeignKey("EnemyLootId");
                                });

                            b1.Navigation("Experience")
                                .IsRequired();

                            b1.Navigation("Gold")
                                .IsRequired();

                            b1.Navigation("Items");
                        });

                    b.Navigation("Loot")
                        .IsRequired();
                });

            modelBuilder.Entity("GameTest.Domain.Entities.EnemyProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Enemy", "Enemy")
                        .WithMany("Properties")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.EnemyStat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Item", b =>
                {
                    b.OwnsOne("GameTest.Domain.ValueObjects.ItemEffect", "Effect", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("EffectDescription");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("EffectName");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("EffectType");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");

                            b1.OwnsMany("GameTest.Domain.ValueObjects.LevelProgression", "Levels", b2 =>
                                {
                                    b2.Property<int>("ItemEffectId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Level")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("Level");

                                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b2.Property<int>("Level"));

                                    b2.Property<int>("Price")
                                        .HasColumnType("int")
                                        .HasColumnName("Price");

                                    b2.Property<float>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("Bonus");

                                    b2.HasKey("ItemEffectId", "Level");

                                    b2.ToTable("Items_Levels");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemEffectId");
                                });

                            b1.Navigation("Levels");
                        });

                    b.OwnsMany("GameTest.Domain.ValueObjects.ItemTemporaryLevel", "TemporaryLevels", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<float>("Bonus")
                                .HasColumnType("float")
                                .HasColumnName("Bonus");

                            b1.Property<int>("Price")
                                .HasColumnType("int")
                                .HasColumnName("Price");

                            b1.HasKey("ItemId", "Level");

                            b1.ToTable("ItemTemporaryLevel");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Effect")
                        .IsRequired();

                    b.Navigation("TemporaryLevels");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerItem", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Player", "Player")
                        .WithMany("Items")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerUnit", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Player", "Player")
                        .WithMany("Units")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerUnitProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.PlayerUnit", "PlayerUnit")
                        .WithMany("Properties")
                        .HasForeignKey("PlayerUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.UnitProperty", "UnitProperty")
                        .WithMany()
                        .HasForeignKey("UnitPropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerUnit");

                    b.Navigation("UnitProperty");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerWeapon", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Player", "Player")
                        .WithMany("Weapons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerWeaponProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.PlayerWeapon", "PlayerWeapon")
                        .WithMany("Properties")
                        .HasForeignKey("PlayerWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.WeaponProperty", "WeaponProperty")
                        .WithMany()
                        .HasForeignKey("WeaponPropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerWeapon");

                    b.Navigation("WeaponProperty");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Run", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Player", "Player")
                        .WithMany("Runs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Unit", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.Weapon", "StartWeapon")
                        .WithMany()
                        .HasForeignKey("StartWeaponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("GameTest.Domain.ValueObjects.TemporaryUpgradeLevel", "TemporaryUpgradeLevels", b1 =>
                        {
                            b1.Property<int>("UnitId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Price")
                                .HasColumnType("int")
                                .HasColumnName("Price");

                            b1.HasKey("UnitId", "Level");

                            b1.ToTable("Units_TemporaryUpgradeLevels");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.OwnsOne("GameTest.Domain.ValueObjects.PassiveAbility", "PassiveAbility", b1 =>
                        {
                            b1.Property<int>("UnitId")
                                .HasColumnType("int");

                            b1.Property<float>("Bonus")
                                .HasColumnType("float")
                                .HasColumnName("PassiveAbilityBonus");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PassiveAbilityDescription");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PassiveAbilityName");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("PassiveAbilityType");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("PassiveAbility")
                        .IsRequired();

                    b.Navigation("StartWeapon");

                    b.Navigation("TemporaryUpgradeLevels");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.UnitProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.UnitStat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Unit", "Unit")
                        .WithMany("Properties")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameTest.Domain.ValueObjects.LevelProgression", "Levels", b1 =>
                        {
                            b1.Property<int>("UnitPropertyId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Price")
                                .HasColumnType("int")
                                .HasColumnName("Price");

                            b1.Property<float>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Value");

                            b1.HasKey("UnitPropertyId", "Level");

                            b1.ToTable("UnitProperties_Levels");

                            b1.WithOwner()
                                .HasForeignKey("UnitPropertyId");
                        });

                    b.OwnsMany("GameTest.Domain.ValueObjects.TemporaryLevel", "TemporaryLevels", b1 =>
                        {
                            b1.Property<int>("UnitPropertyId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<float>("Bonus")
                                .HasColumnType("float")
                                .HasColumnName("Bonus");

                            b1.HasKey("UnitPropertyId", "Level");

                            b1.ToTable("UnitProperties_TemporaryLevels");

                            b1.WithOwner()
                                .HasForeignKey("UnitPropertyId");
                        });

                    b.Navigation("Levels");

                    b.Navigation("Stat");

                    b.Navigation("TemporaryLevels");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Wave", b =>
                {
                    b.OwnsMany("GameTest.Domain.ValueObjects.WaveEnemy", "Enemies", b1 =>
                        {
                            b1.Property<int>("WaveId")
                                .HasColumnType("int");

                            b1.Property<int>("EnemyId")
                                .HasColumnType("int")
                                .HasColumnName("EnemyId");

                            b1.Property<int>("SpawnInterval")
                                .HasColumnType("int")
                                .HasColumnName("SpawnInterval");

                            b1.HasKey("WaveId", "EnemyId");

                            b1.HasIndex("EnemyId");

                            b1.ToTable("WaveEnemy");

                            b1.HasOne("GameTest.Domain.Entities.Enemy", null)
                                .WithMany()
                                .HasForeignKey("EnemyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WaveId");

                            b1.OwnsOne("GameTest.Domain.ValueObjects.EnemyQuantityRange", "QuantityRange", b2 =>
                                {
                                    b2.Property<int>("WaveEnemyWaveId")
                                        .HasColumnType("int");

                                    b2.Property<int>("WaveEnemyEnemyId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int")
                                        .HasColumnName("QuantityMax");

                                    b2.Property<int>("Min")
                                        .HasColumnType("int")
                                        .HasColumnName("QuantityMin");

                                    b2.HasKey("WaveEnemyWaveId", "WaveEnemyEnemyId");

                                    b2.ToTable("WaveEnemy");

                                    b2.WithOwner()
                                        .HasForeignKey("WaveEnemyWaveId", "WaveEnemyEnemyId");
                                });

                            b1.Navigation("QuantityRange")
                                .IsRequired();
                        });

                    b.Navigation("Enemies");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Weapon", b =>
                {
                    b.OwnsMany("GameTest.Domain.ValueObjects.TemporaryUpgradeLevel", "TemporaryUpgradeLevels", b1 =>
                        {
                            b1.Property<int>("WeaponId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Price")
                                .HasColumnType("int")
                                .HasColumnName("Price");

                            b1.HasKey("WeaponId", "Level");

                            b1.ToTable("Weapons_TemporaryUpgradeLevels");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("TemporaryUpgradeLevels");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.WeaponProperty", b =>
                {
                    b.HasOne("GameTest.Domain.Entities.WeaponStat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameTest.Domain.Entities.Weapon", "Weapon")
                        .WithMany("Properties")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameTest.Domain.ValueObjects.TemporaryLevel", "TemporaryLevels", b1 =>
                        {
                            b1.Property<int>("UnitPropertyId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<float>("Bonus")
                                .HasColumnType("float")
                                .HasColumnName("Bonus");

                            b1.HasKey("UnitPropertyId", "Level");

                            b1.ToTable("WeaponProperties_TemporaryLevels");

                            b1.WithOwner()
                                .HasForeignKey("UnitPropertyId");
                        });

                    b.OwnsMany("GameTest.Domain.ValueObjects.LevelProgression", "Levels", b1 =>
                        {
                            b1.Property<int>("WeaponPropertyId")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Price")
                                .HasColumnType("int")
                                .HasColumnName("Price");

                            b1.Property<float>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Value");

                            b1.HasKey("WeaponPropertyId", "Level");

                            b1.ToTable("WeaponProperties_Levels");

                            b1.WithOwner()
                                .HasForeignKey("WeaponPropertyId");
                        });

                    b.Navigation("Levels");

                    b.Navigation("Stat");

                    b.Navigation("TemporaryLevels");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Cat", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Enemy", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Player", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Runs");

                    b.Navigation("Units");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerUnit", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.PlayerWeapon", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GameTest.Domain.Entities.Weapon", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
